
# Complete recipe data for seniors-recipes wiki
# All quantities in metric. Nutrients are estimates per serving.

RECIPES = [
    # ── ONE-PAN DINNERS ──────────────────────────────────────────────────────
    {
        "id": "chicken-veggie-tray-bake",
        "title": "Chicken & Veggie Tray Bake",
        "category": "One-Pan Dinners",
        "description": "Chicken thighs, vegetables, and potatoes roasted on one sheet pan, perfumed with lemon.",
        "servings": 1,
        "ingredients": [
            "2 chicken thighs (≈300 g), bone-in, skin-on",
            "200 g baby potatoes, halved",
            "1 medium zucchini (≈150 g), sliced",
            "1 red capsicum (≈120 g), roughly chopped",
            "2 tbsp (30 ml) olive oil",
            "2 garlic cloves, minced",
            "1 tsp dried oregano",
            "½ lemon, sliced",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Preheat oven to 200 °C (fan 180 °C).",
            "Place potatoes on a large baking tray and drizzle with 1 tbsp olive oil. Roast 10 min.",
            "Add chicken thighs, zucchini, and capsicum. Drizzle with remaining oil, scatter garlic, oregano, salt and pepper.",
            "Tuck lemon slices underneath the chicken.",
            "Roast a further 30–35 min until chicken skin is golden and potatoes are tender.",
            "Rest 5 min before serving.",
        ],
        "nutrients": {"calories": 620, "protein_g": 45, "carbs_g": 38, "fat_g": 30, "fibre_g": 6},
    },
    {
        "id": "salmon-honey-garlic-broccoli",
        "title": "Salmon with Honey Garlic Broccoli",
        "category": "One-Pan Dinners",
        "description": "Salmon fillet and broccoli roasted together with a quick glaze of honey, garlic and soy.",
        "servings": 1,
        "ingredients": [
            "1 salmon fillet (≈180 g)",
            "200 g broccoli florets",
            "1 tbsp (15 ml) honey",
            "1 tbsp (15 ml) soy sauce (low-sodium)",
            "2 garlic cloves, minced",
            "1 tbsp (15 ml) olive oil",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Preheat oven to 200 °C.",
            "Mix honey, soy sauce, and garlic in a small bowl.",
            "Place broccoli on a baking tray, drizzle with olive oil, season.",
            "Nestle salmon on top of broccoli and spoon glaze over everything.",
            "Bake 18–20 min until salmon flakes easily.",
        ],
        "nutrients": {"calories": 480, "protein_g": 42, "carbs_g": 22, "fat_g": 22, "fibre_g": 5},
    },
    {
        "id": "sheetpan-sausage-cabbage-apples",
        "title": "Sheetpan Sausage, Cabbage & Apples",
        "category": "One-Pan Dinners",
        "description": "Smoked sausage roasted alongside sweet apples and cabbage, finished with a drizzle of mustard.",
        "servings": 1,
        "ingredients": [
            "2 smoked chicken sausages (≈200 g), sliced",
            "200 g green cabbage, roughly chopped",
            "1 medium apple (≈150 g), cored and sliced",
            "1 tbsp (15 ml) olive oil",
            "1 tsp whole-grain mustard",
            "½ tsp caraway seeds (optional)",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Preheat oven to 200 °C.",
            "Toss cabbage and apple with olive oil, salt, pepper, and caraway seeds on a baking tray.",
            "Add sausage slices on top.",
            "Roast 25 min, stirring once halfway.",
            "Drizzle mustard over everything and return to oven for 5 min.",
        ],
        "nutrients": {"calories": 520, "protein_g": 28, "carbs_g": 32, "fat_g": 28, "fibre_g": 7},
    },
    {
        "id": "lemon-herb-tilapia-green-beans",
        "title": "Lemon Herb Tilapia with Green Beans",
        "category": "One-Pan Dinners",
        "description": "Tilapia and green beans baked with lemon butter, herbs, and optional cherry tomatoes.",
        "servings": 1,
        "ingredients": [
            "1 tilapia fillet (≈200 g)",
            "150 g green beans, trimmed",
            "10 cherry tomatoes (optional)",
            "1 tbsp (15 g) butter",
            "1 lemon, juice and zest",
            "1 tsp mixed dried herbs",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Preheat oven to 190 °C.",
            "Arrange green beans and tomatoes on a lined baking tray.",
            "Place tilapia on top. Dot with butter, squeeze lemon, add zest and herbs.",
            "Bake 18–20 min until fish is opaque and flakes easily.",
        ],
        "nutrients": {"calories": 340, "protein_g": 40, "carbs_g": 12, "fat_g": 14, "fibre_g": 5},
    },
    {
        "id": "ground-turkey-cabbage-roll",
        "title": "One-Pan Ground Turkey Cabbage Roll",
        "category": "One-Pan Dinners",
        "description": "A skillet meal capturing cabbage roll flavours with ground turkey, rice and tomato sauce.",
        "servings": 1,
        "ingredients": [
            "150 g lean ground turkey",
            "150 g green cabbage, shredded",
            "60 g (dry) long-grain rice",
            "200 ml tomato passata",
            "1 small onion, diced",
            "1 garlic clove, minced",
            "1 tsp olive oil",
            "½ tsp smoked paprika",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Heat oil in a large non-stick skillet over medium heat.",
            "Cook onion 3 min, add garlic, cook 1 min.",
            "Add turkey, break up and cook until no longer pink, about 5 min.",
            "Add cabbage, passata, paprika, salt and pepper. Stir.",
            "Add rice and 150 ml water. Bring to a boil.",
            "Cover, reduce heat and simmer 18–20 min until rice is cooked.",
        ],
        "nutrients": {"calories": 490, "protein_g": 38, "carbs_g": 52, "fat_g": 10, "fibre_g": 6},
    },
    {
        "id": "shrimp-veggie-stir-fry",
        "title": "One-Pan Shrimp & Veggie Stir-Fry",
        "category": "One-Pan Dinners",
        "description": "Quick-cooking shrimp and mixed vegetables tossed in soy and garlic, served over microwave rice.",
        "servings": 1,
        "ingredients": [
            "150 g raw shrimp, peeled and deveined",
            "1 cup (≈100 g) mixed stir-fry vegetables (frozen is fine)",
            "1 tbsp (15 ml) soy sauce (low-sodium)",
            "1 tsp sesame oil",
            "1 garlic clove, minced",
            "1 tsp fresh ginger, grated",
            "1 sachet (250 g) microwave brown rice",
            "1 tsp olive oil",
        ],
        "steps": [
            "Microwave rice according to packet instructions; set aside.",
            "Heat olive oil in a wok or large frying pan over high heat.",
            "Add garlic and ginger; stir-fry 30 seconds.",
            "Add vegetables; stir-fry 3 min.",
            "Add shrimp; cook 2–3 min until pink.",
            "Drizzle soy sauce and sesame oil; toss well.",
            "Serve over rice.",
        ],
        "nutrients": {"calories": 420, "protein_g": 32, "carbs_g": 48, "fat_g": 10, "fibre_g": 5},
    },
    {
        "id": "sweet-potato-black-bean-bowl",
        "title": "Sweet Potato & Black Bean Fiesta Bowl",
        "category": "One-Pan Dinners",
        "description": "Roasted sweet potatoes, black beans, corn and onion seasoned with cumin and chilli powder.",
        "servings": 1,
        "ingredients": [
            "1 medium sweet potato (≈200 g), cubed",
            "½ can (≈200 g) black beans, drained and rinsed",
            "80 g corn kernels (frozen or canned)",
            "½ red onion, sliced",
            "1 tbsp (15 ml) olive oil",
            "½ tsp ground cumin",
            "½ tsp chilli powder",
            "Salt and pepper to taste",
            "2 tbsp Greek yoghurt to serve",
        ],
        "steps": [
            "Preheat oven to 210 °C.",
            "Toss sweet potato and onion with olive oil, cumin, chilli, salt and pepper.",
            "Spread on a baking tray; roast 20 min.",
            "Add black beans and corn; roast a further 10 min.",
            "Serve topped with Greek yoghurt.",
        ],
        "nutrients": {"calories": 450, "protein_g": 18, "carbs_g": 70, "fat_g": 10, "fibre_g": 14},
    },
    {
        "id": "pasta-primavera",
        "title": "One-Pan Pasta Primavera",
        "category": "One-Pan Dinners",
        "description": "Dry pasta, cherry tomatoes, mushrooms, onions, and spinach simmered in one skillet with broth.",
        "servings": 1,
        "ingredients": [
            "80 g dry pasta (penne or fusilli)",
            "100 g cherry tomatoes, halved",
            "80 g mushrooms, sliced",
            "½ small onion, diced",
            "40 g baby spinach",
            "350 ml vegetable stock",
            "1 garlic clove, minced",
            "1 tbsp (15 ml) olive oil",
            "2 tbsp grated Parmesan",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Combine pasta, tomatoes, mushrooms, onion, garlic, stock and olive oil in a large saucepan.",
            "Bring to a boil over medium-high heat.",
            "Cook uncovered, stirring frequently, until pasta is al dente and liquid mostly absorbed (10–12 min).",
            "Stir through spinach until wilted.",
            "Season and top with Parmesan.",
        ],
        "nutrients": {"calories": 450, "protein_g": 18, "carbs_g": 68, "fat_g": 12, "fibre_g": 6},
    },
    {
        "id": "mediterranean-chicken-olives",
        "title": "Mediterranean Chicken with Olives & Tomatoes",
        "category": "One-Pan Dinners",
        "description": "Chicken thighs baked with cherry tomatoes, olives, garlic and olive oil for a natural, savory sauce.",
        "servings": 1,
        "ingredients": [
            "2 chicken thighs (≈300 g), bone-in",
            "100 g cherry tomatoes",
            "40 g pitted kalamata olives",
            "2 garlic cloves, crushed",
            "1 tbsp (15 ml) olive oil",
            "½ tsp dried oregano",
            "½ lemon, squeezed",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Preheat oven to 200 °C.",
            "Place chicken in a small baking dish. Scatter tomatoes, olives and garlic around.",
            "Drizzle olive oil and lemon juice over everything. Season with oregano, salt and pepper.",
            "Bake 35–40 min until chicken is cooked through and sauce is bubbling.",
            "Serve with crusty bread or steamed greens.",
        ],
        "nutrients": {"calories": 560, "protein_g": 44, "carbs_g": 8, "fat_g": 38, "fibre_g": 3},
    },
    {
        "id": "baked-egg-frittata",
        "title": "One-Pan Baked Egg Frittata",
        "category": "One-Pan Dinners",
        "description": "A fluffy baked frittata made by pouring whisked eggs over spinach, tomatoes and onions.",
        "servings": 1,
        "ingredients": [
            "3 large eggs",
            "40 g baby spinach",
            "5 cherry tomatoes, halved",
            "¼ small onion, finely diced",
            "30 g feta cheese, crumbled",
            "1 tsp olive oil",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Preheat oven to 180 °C.",
            "Heat oil in a small oven-safe frying pan over medium heat. Sauté onion 3 min.",
            "Add spinach; cook until wilted. Add tomatoes.",
            "Whisk eggs with salt and pepper; pour over vegetables.",
            "Scatter feta on top. Transfer to oven.",
            "Bake 12–15 min until eggs are set and top is lightly golden.",
        ],
        "nutrients": {"calories": 330, "protein_g": 26, "carbs_g": 8, "fat_g": 22, "fibre_g": 2},
    },

    # ── MINIMAL COOKING HIGH-PROTEIN & HIGH-FIBRE ────────────────────────────
    {
        "id": "egg-spinach-white-bean-skillet",
        "title": "Warm Egg, Spinach & White Bean Skillet",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Soft white beans and fresh spinach heated in a skillet, topped with a cooked egg.",
        "servings": 1,
        "ingredients": [
            "½ can (≈200 g) white cannellini beans, drained",
            "60 g baby spinach",
            "2 large eggs",
            "1 garlic clove, minced",
            "1 tbsp (15 ml) olive oil",
            "Pinch chilli flakes",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Heat oil in a small skillet. Add garlic and chilli; cook 1 min.",
            "Add beans and spinach; stir until spinach wilts and beans are warmed (3 min).",
            "Make 2 wells; crack an egg into each.",
            "Cover and cook over low heat 4–5 min until whites are set.",
            "Season and serve directly from the skillet.",
        ],
        "nutrients": {"calories": 380, "protein_g": 26, "carbs_g": 28, "fat_g": 18, "fibre_g": 9},
    },
    {
        "id": "peanut-butter-banana-oatmeal",
        "title": "Warm Peanut Butter Banana Oatmeal",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Rolled oats cooked in milk, enriched with peanut butter, sliced banana and cinnamon.",
        "servings": 1,
        "ingredients": [
            "60 g rolled oats",
            "240 ml reduced-fat milk",
            "1 ripe banana, sliced",
            "2 tbsp (32 g) natural peanut butter",
            "½ tsp ground cinnamon",
            "1 tsp honey (optional)",
        ],
        "steps": [
            "Combine oats and milk in a small saucepan over medium heat.",
            "Cook, stirring, 4–5 min until thick and creamy.",
            "Stir in peanut butter and cinnamon.",
            "Top with banana slices and a drizzle of honey if using.",
        ],
        "nutrients": {"calories": 520, "protein_g": 22, "carbs_g": 68, "fat_g": 18, "fibre_g": 8},
    },
    {
        "id": "tuna-chickpea-warm-skillet",
        "title": "Tuna & Chickpea Warm Skillet",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Canned chickpeas and diced onions warmed in a pan, gently tossed with canned tuna, lemon and black pepper.",
        "servings": 1,
        "ingredients": [
            "1 can (185 g) tuna in springwater, drained",
            "½ can (≈200 g) chickpeas, drained and rinsed",
            "½ small red onion, finely diced",
            "1 lemon, juiced",
            "1 tbsp (15 ml) olive oil",
            "Handful flat-leaf parsley, chopped",
            "Black pepper to taste",
        ],
        "steps": [
            "Heat oil in a small saucepan. Add onion; cook 2 min.",
            "Add chickpeas; warm through 3 min.",
            "Remove from heat, stir in tuna, lemon juice and parsley.",
            "Season with black pepper and serve warm.",
        ],
        "nutrients": {"calories": 390, "protein_g": 38, "carbs_g": 28, "fat_g": 12, "fibre_g": 7},
    },
    {
        "id": "warm-lentil-tomato-bowl",
        "title": "Warm Lentil & Tomato Comfort Bowl",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Canned lentils warmed with diced tomatoes, olive oil and garlic powder for a quick stew-like meal.",
        "servings": 1,
        "ingredients": [
            "1 can (400 g) lentils, drained and rinsed",
            "1 can (400 g) diced tomatoes",
            "½ tsp garlic powder",
            "½ tsp ground cumin",
            "1 tbsp (15 ml) olive oil",
            "Salt and pepper to taste",
            "Fresh parsley to serve",
        ],
        "steps": [
            "Combine lentils, tomatoes, garlic powder, cumin and olive oil in a saucepan.",
            "Simmer over medium heat 8–10 min, stirring occasionally.",
            "Season. Serve in a bowl topped with parsley.",
        ],
        "nutrients": {"calories": 360, "protein_g": 22, "carbs_g": 48, "fat_g": 8, "fibre_g": 14},
    },
    {
        "id": "cottage-cheese-apple-skillet",
        "title": "Cottage Cheese & Warm Apple Skillet",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Apples sautéed in butter with cinnamon, served over a bowl of cottage cheese and walnuts.",
        "servings": 1,
        "ingredients": [
            "200 g low-fat cottage cheese",
            "1 medium apple, cored and sliced",
            "1 tsp (5 g) butter",
            "½ tsp cinnamon",
            "1 tbsp (10 g) walnuts, roughly chopped",
            "1 tsp honey",
        ],
        "steps": [
            "Melt butter in a small frying pan over medium heat.",
            "Add apple slices and cinnamon; cook 3–4 min until just tender.",
            "Spoon cottage cheese into a bowl.",
            "Top with warm apple, walnuts and honey.",
        ],
        "nutrients": {"calories": 320, "protein_g": 24, "carbs_g": 32, "fat_g": 10, "fibre_g": 4},
    },
    {
        "id": "sardine-avocado-toast",
        "title": "Simple Sardine & Avocado Toast",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Mashed avocado spread on whole-grain toast, topped with canned sardines and a squeeze of lemon.",
        "servings": 1,
        "ingredients": [
            "2 slices whole-grain bread, toasted",
            "½ ripe avocado (≈80 g)",
            "1 can (105 g) sardines in olive oil, drained",
            "½ lemon, juiced",
            "Salt, pepper and chilli flakes to taste",
        ],
        "steps": [
            "Toast bread.",
            "Mash avocado with lemon juice, salt and pepper.",
            "Spread onto toast.",
            "Top with sardines. Sprinkle chilli flakes.",
        ],
        "nutrients": {"calories": 420, "protein_g": 32, "carbs_g": 30, "fat_g": 20, "fibre_g": 7},
    },
    {
        "id": "chicken-bean-warm-wrap",
        "title": "Chicken & Bean Warm Wrap",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Black beans, cooked chicken and salsa warmed in a skillet and rolled into a whole-grain tortilla.",
        "servings": 1,
        "ingredients": [
            "1 whole-grain tortilla (≈60 g)",
            "100 g cooked chicken breast, shredded",
            "½ can (≈200 g) black beans, drained",
            "3 tbsp (45 g) tomato salsa",
            "30 g reduced-fat cheddar, grated",
            "1 tsp olive oil",
        ],
        "steps": [
            "Heat oil in a small pan. Add beans and salsa; warm 3 min.",
            "Add chicken; stir and heat through.",
            "Warm tortilla in a dry pan or microwave 20 sec.",
            "Fill with bean mixture and cheese. Roll and serve.",
        ],
        "nutrients": {"calories": 490, "protein_g": 42, "carbs_g": 48, "fat_g": 12, "fibre_g": 10},
    },
    {
        "id": "quinoa-egg-breakfast-bowl",
        "title": "Quinoa Egg Breakfast Bowl",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Warmed leftover quinoa topped with a cooked egg and a sprinkle of pumpkin seeds.",
        "servings": 1,
        "ingredients": [
            "150 g cooked quinoa (leftover or microwave sachet)",
            "2 large eggs",
            "1 tbsp (10 g) pumpkin seeds",
            "1 tsp olive oil",
            "Salt and pepper to taste",
            "Hot sauce (optional)",
        ],
        "steps": [
            "Warm quinoa in a saucepan or microwave.",
            "Fry or poach eggs to your liking.",
            "Place quinoa in a bowl, top with eggs and pumpkin seeds.",
            "Season and add hot sauce if desired.",
        ],
        "nutrients": {"calories": 400, "protein_g": 26, "carbs_g": 36, "fat_g": 16, "fibre_g": 5},
    },
    {
        "id": "warm-greek-yogurt-berry-oats",
        "title": "Warm Greek Yoghurt Berry Oats",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Oats and frozen berries cooked in water, folded through Greek yoghurt for a protein-rich bowl.",
        "servings": 1,
        "ingredients": [
            "60 g rolled oats",
            "100 g frozen mixed berries",
            "180 ml water",
            "120 g full-fat Greek yoghurt",
            "1 tbsp (15 ml) honey",
            "1 tbsp (10 g) chia seeds",
        ],
        "steps": [
            "Cook oats with water 4–5 min until soft.",
            "Stir in frozen berries; heat 2 min more until berries are warm and burst.",
            "Remove from heat; fold in Greek yoghurt.",
            "Top with honey and chia seeds.",
        ],
        "nutrients": {"calories": 430, "protein_g": 20, "carbs_g": 60, "fat_g": 10, "fibre_g": 9},
    },
    {
        "id": "smoked-salmon-scrambled-eggs",
        "title": "Smoked Salmon Scrambled Eggs",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Creamy scrambled eggs topped with smoked salmon and capers on whole-grain toast.",
        "servings": 1,
        "ingredients": [
            "3 large eggs",
            "60 g smoked salmon",
            "1 tbsp (15 g) butter",
            "2 tbsp (30 ml) reduced-fat milk",
            "1 tbsp capers",
            "2 slices whole-grain toast",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Whisk eggs with milk, salt and pepper.",
            "Melt butter in a small non-stick pan over low heat. Add eggs.",
            "Stir gently with a spatula until just set and creamy (3–4 min).",
            "Serve on toast topped with smoked salmon and capers.",
        ],
        "nutrients": {"calories": 450, "protein_g": 38, "carbs_g": 28, "fat_g": 20, "fibre_g": 3},
    },
    {
        "id": "edamame-tofu-brown-rice",
        "title": "Edamame, Tofu & Brown Rice Bowl",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Firm tofu cubes and shelled edamame served over brown rice with a soy-ginger drizzle.",
        "servings": 1,
        "ingredients": [
            "150 g firm tofu, cubed",
            "80 g frozen edamame (shelled), thawed",
            "1 sachet (250 g) microwave brown rice",
            "1 tbsp (15 ml) soy sauce",
            "1 tsp sesame oil",
            "1 tsp fresh ginger, grated",
            "1 tsp sesame seeds",
            "1 spring onion, sliced",
        ],
        "steps": [
            "Microwave rice and edamame according to packet directions.",
            "Mix soy sauce, sesame oil and ginger in a small bowl.",
            "Place rice in a bowl, top with tofu and edamame.",
            "Drizzle with sauce; sprinkle sesame seeds and spring onion.",
        ],
        "nutrients": {"calories": 480, "protein_g": 28, "carbs_g": 56, "fat_g": 16, "fibre_g": 8},
    },
    {
        "id": "lentil-egg-shakshuka",
        "title": "Quick Lentil & Egg Shakshuka",
        "category": "Minimal Cooking High-Protein & High-Fibre",
        "description": "Spiced tomato-lentil sauce with eggs poached directly in the pan.",
        "servings": 1,
        "ingredients": [
            "½ can (≈200 g) lentils, drained",
            "½ can (≈200 g) diced tomatoes",
            "2 large eggs",
            "½ tsp cumin",
            "½ tsp smoked paprika",
            "1 garlic clove, minced",
            "1 tbsp (15 ml) olive oil",
            "Salt and pepper to taste",
            "Fresh coriander to serve",
        ],
        "steps": [
            "Heat oil in a small saucepan. Add garlic, cumin, paprika; stir 1 min.",
            "Add tomatoes and lentils; simmer 5 min.",
            "Make 2 wells; crack eggs in.",
            "Cover, cook 5–6 min until whites are just set.",
            "Top with coriander and serve with crusty bread.",
        ],
        "nutrients": {"calories": 380, "protein_g": 26, "carbs_g": 30, "fat_g": 14, "fibre_g": 9},
    },

    # ── SIMPLE TOFU RECIPES ──────────────────────────────────────────────────
    {
        "id": "garlic-soy-tofu-bowl",
        "title": "Garlic Soy Tofu Bowl",
        "category": "Simple Tofu Recipes",
        "description": "Tofu cubes gently warmed in a pan with olive oil, minced garlic and soy sauce.",
        "servings": 1,
        "ingredients": [
            "200 g firm tofu, cubed",
            "2 garlic cloves, minced",
            "1 tbsp (15 ml) soy sauce (low-sodium)",
            "1 tsp olive oil",
            "1 tsp sesame oil",
            "1 spring onion, sliced",
            "1 sachet (250 g) microwave rice to serve",
        ],
        "steps": [
            "Pat tofu dry with paper towel.",
            "Heat olive oil in a pan over medium heat. Add garlic; cook 1 min.",
            "Add tofu; cook 4–5 min, turning, until lightly golden.",
            "Drizzle with soy sauce and sesame oil; toss gently.",
            "Serve over rice, topped with spring onion.",
        ],
        "nutrients": {"calories": 400, "protein_g": 22, "carbs_g": 48, "fat_g": 14, "fibre_g": 3},
    },
    {
        "id": "savory-tofu-scramble",
        "title": "Savoury Tofu Scramble",
        "category": "Simple Tofu Recipes",
        "description": "Crumbled firm tofu cooked in butter with turmeric to mimic scrambled eggs.",
        "servings": 1,
        "ingredients": [
            "200 g firm tofu, crumbled",
            "1 tsp (5 g) butter",
            "2 tbsp (30 ml) reduced-fat milk",
            "¼ tsp turmeric",
            "Salt and pepper to taste",
            "Whole-grain toast to serve",
        ],
        "steps": [
            "Melt butter in a non-stick pan over medium-low heat.",
            "Add crumbled tofu, milk and turmeric.",
            "Stir gently until heated through and slightly dry, about 5 min.",
            "Season and serve on toast.",
        ],
        "nutrients": {"calories": 300, "protein_g": 22, "carbs_g": 20, "fat_g": 14, "fibre_g": 2},
    },
    {
        "id": "tomato-braised-tofu",
        "title": "Tomato Braised Tofu",
        "category": "Simple Tofu Recipes",
        "description": "Tofu cubes simmered in a light sauce made from broken-down canned tomatoes and olive oil.",
        "servings": 1,
        "ingredients": [
            "200 g firm tofu, cubed",
            "½ can (≈200 g) crushed tomatoes",
            "1 garlic clove, minced",
            "1 tbsp (15 ml) olive oil",
            "½ tsp dried basil",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Heat oil in a saucepan over medium heat. Add garlic; cook 1 min.",
            "Add tomatoes and basil; simmer 5 min.",
            "Add tofu cubes; simmer gently 8 min until sauce thickens slightly.",
            "Season and serve with crusty bread or over pasta.",
        ],
        "nutrients": {"calories": 280, "protein_g": 18, "carbs_g": 14, "fat_g": 16, "fibre_g": 4},
    },
    {
        "id": "light-onion-gravy-tofu",
        "title": "Light Onion Gravy Tofu",
        "category": "Simple Tofu Recipes",
        "description": "Soft tofu warmed in a gentle gravy made from slow-cooked onions and vegetable stock.",
        "servings": 1,
        "ingredients": [
            "200 g soft tofu, sliced",
            "1 large onion, thinly sliced",
            "200 ml vegetable stock",
            "1 tsp (5 g) butter",
            "1 tsp soy sauce",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Melt butter in a saucepan over low heat. Add onion; cook slowly 10 min until golden.",
            "Add stock and soy sauce; simmer 5 min.",
            "Slide in tofu slices; heat gently 3 min.",
            "Serve over mashed potato or rice.",
        ],
        "nutrients": {"calories": 240, "protein_g": 14, "carbs_g": 18, "fat_g": 10, "fibre_g": 3},
    },
    {
        "id": "soft-tofu-vegetable-soup",
        "title": "Soft Tofu Vegetable Soup",
        "category": "Simple Tofu Recipes",
        "description": "A comforting bowl of broth with sliced carrots, silken tofu, soy sauce and fresh spinach.",
        "servings": 1,
        "ingredients": [
            "150 g silken tofu, cubed",
            "400 ml vegetable stock",
            "1 medium carrot (≈80 g), thinly sliced",
            "40 g baby spinach",
            "1 tbsp (15 ml) soy sauce",
            "1 tsp sesame oil",
            "1 spring onion, sliced",
        ],
        "steps": [
            "Bring stock to a simmer in a saucepan. Add carrot; cook 5 min.",
            "Add silken tofu cubes; simmer gently 3 min.",
            "Stir in spinach and soy sauce; cook 1 min until spinach wilts.",
            "Drizzle sesame oil; top with spring onion.",
        ],
        "nutrients": {"calories": 200, "protein_g": 14, "carbs_g": 12, "fat_g": 8, "fibre_g": 3},
    },
    {
        "id": "pan-seared-tofu-herbs",
        "title": "Pan-Seared Tofu with Pepper & Herbs",
        "category": "Simple Tofu Recipes",
        "description": "Firm tofu cubes lightly browned in oil and seasoned with salt, black pepper and dried herbs.",
        "servings": 1,
        "ingredients": [
            "200 g firm tofu, cubed",
            "1 tbsp (15 ml) olive oil",
            "½ tsp dried mixed herbs",
            "½ tsp black pepper",
            "Salt to taste",
            "Salad greens to serve",
        ],
        "steps": [
            "Pat tofu dry. Season with herbs, pepper and salt.",
            "Heat oil in a non-stick pan over medium-high heat.",
            "Add tofu; cook 3–4 min each side until golden.",
            "Serve over salad greens.",
        ],
        "nutrients": {"calories": 250, "protein_g": 18, "carbs_g": 4, "fat_g": 18, "fibre_g": 1},
    },
    {
        "id": "tofu-mashed-potato-gravy",
        "title": "Tofu with Mashed Potato & Gravy",
        "category": "Simple Tofu Recipes",
        "description": "Warm tofu cubes served over soft mashed potato and smothered in warm gravy.",
        "servings": 1,
        "ingredients": [
            "200 g firm tofu, cubed",
            "2 medium potatoes (≈300 g), peeled and cubed",
            "2 tbsp (30 ml) reduced-fat milk",
            "1 tsp (5 g) butter",
            "200 ml ready-made gravy (low-sodium)",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Boil potatoes 15 min until tender; drain and mash with milk, butter, salt and pepper.",
            "Warm gravy in a small saucepan; add tofu cubes and heat through 3 min.",
            "Serve tofu and gravy over mashed potato.",
        ],
        "nutrients": {"calories": 430, "protein_g": 22, "carbs_g": 56, "fat_g": 12, "fibre_g": 5},
    },
    {
        "id": "ginger-soy-tofu",
        "title": "Ginger Soy Tofu",
        "category": "Simple Tofu Recipes",
        "description": "Tofu warmed in a skillet with soy sauce and fresh or powdered ginger for a mildly spicy aroma.",
        "servings": 1,
        "ingredients": [
            "200 g firm tofu, sliced",
            "1 tbsp (15 ml) soy sauce (low-sodium)",
            "1 tsp fresh ginger, grated (or ½ tsp ground)",
            "1 tsp sesame oil",
            "1 tsp honey",
            "1 tsp olive oil",
            "Rice or noodles to serve",
        ],
        "steps": [
            "Mix soy sauce, ginger, sesame oil and honey in a small bowl.",
            "Heat olive oil in a pan over medium heat.",
            "Add tofu slices; cook 3 min each side.",
            "Pour sauce over tofu; cook 1 min until glazed.",
            "Serve with rice or noodles.",
        ],
        "nutrients": {"calories": 280, "protein_g": 18, "carbs_g": 14, "fat_g": 16, "fibre_g": 1},
    },
    {
        "id": "cabbage-tofu-stir",
        "title": "Cabbage & Tofu Stir",
        "category": "Simple Tofu Recipes",
        "description": "Budget-friendly chopped cabbage softened in a pan, then tossed with tofu cubes and soy sauce.",
        "servings": 1,
        "ingredients": [
            "200 g firm tofu, cubed",
            "200 g green cabbage, shredded",
            "1 garlic clove, minced",
            "1 tbsp (15 ml) soy sauce",
            "1 tsp sesame oil",
            "1 tsp olive oil",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Heat olive oil in a wok or large frying pan over medium-high heat.",
            "Add garlic; stir-fry 30 sec.",
            "Add cabbage; stir-fry 4 min until softened.",
            "Add tofu and soy sauce; toss gently 2 min.",
            "Drizzle sesame oil, season and serve.",
        ],
        "nutrients": {"calories": 290, "protein_g": 20, "carbs_g": 16, "fat_g": 16, "fibre_g": 5},
    },
    {
        "id": "no-energy-savory-tofu-bowl",
        "title": "No-Energy Savoury Tofu Bowl",
        "category": "Simple Tofu Recipes",
        "description": "Raw or barely-warmed tofu placed in a bowl and simply dressed with soy sauce.",
        "servings": 1,
        "ingredients": [
            "200 g silken or soft tofu",
            "1 tbsp (15 ml) soy sauce",
            "1 tsp sesame oil",
            "1 spring onion, thinly sliced",
            "1 tsp sesame seeds",
            "Pinch chilli flakes (optional)",
        ],
        "steps": [
            "Scoop tofu into a bowl (no cooking needed).",
            "Drizzle with soy sauce and sesame oil.",
            "Top with spring onion, sesame seeds and chilli flakes.",
        ],
        "nutrients": {"calories": 180, "protein_g": 12, "carbs_g": 6, "fat_g": 12, "fibre_g": 0},
    },

    # ── NO-COOK HEALTHY SNACK PLATES ─────────────────────────────────────────
    {
        "id": "protein-power-no-effort-plate",
        "title": "Protein Power No-Effort Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "Halved boiled eggs, fanned avocado, cherry tomatoes, and stacked whole-grain crackers.",
        "servings": 1,
        "ingredients": [
            "2 hard-boiled eggs, halved",
            "½ avocado, sliced",
            "6 cherry tomatoes",
            "4–6 whole-grain crackers",
            "Salt and pepper to taste",
            "Lemon wedge to serve",
        ],
        "steps": [
            "Arrange ingredients on a plate.",
            "Season eggs and avocado with salt and pepper.",
            "Serve with a lemon wedge.",
        ],
        "nutrients": {"calories": 350, "protein_g": 18, "carbs_g": 22, "fat_g": 22, "fibre_g": 6},
    },
    {
        "id": "sweet-savory-balance-plate",
        "title": "Sweet & Savoury Balance Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "Greek yoghurt swirled with honey, served alongside sliced fresh apple and walnuts.",
        "servings": 1,
        "ingredients": [
            "150 g full-fat Greek yoghurt",
            "1 medium apple, cored and sliced",
            "1 tbsp (15 ml) honey",
            "30 g walnuts",
        ],
        "steps": [
            "Spoon yoghurt into a bowl; swirl in honey.",
            "Arrange apple slices and walnuts alongside.",
        ],
        "nutrients": {"calories": 340, "protein_g": 14, "carbs_g": 36, "fat_g": 16, "fibre_g": 4},
    },
    {
        "id": "no-cook-chicken-plate",
        "title": "No-Cook Chicken Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "Shredded rotisserie chicken over a bed of greens, drizzled with olive oil and vinegar.",
        "servings": 1,
        "ingredients": [
            "150 g rotisserie chicken, shredded",
            "60 g mixed salad greens",
            "6 cherry tomatoes, halved",
            "1 tbsp (15 ml) extra-virgin olive oil",
            "1 tsp balsamic vinegar",
            "Salt and pepper to taste",
        ],
        "steps": [
            "Arrange greens on a plate.",
            "Top with chicken and tomatoes.",
            "Drizzle olive oil and vinegar; season.",
        ],
        "nutrients": {"calories": 340, "protein_g": 36, "carbs_g": 6, "fat_g": 18, "fibre_g": 2},
    },
    {
        "id": "tuna-without-fuss-plate",
        "title": "Tuna Without the Fuss Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "Canned tuna mixed with mayo or yoghurt, served with crisp cucumber slices and crackers.",
        "servings": 1,
        "ingredients": [
            "1 can (185 g) tuna in springwater, drained",
            "1 tbsp (15 g) light mayonnaise or Greek yoghurt",
            "½ cucumber, sliced",
            "6 whole-grain crackers",
            "Salt and pepper to taste",
            "Lemon wedge",
        ],
        "steps": [
            "Mix tuna with mayo or yoghurt, salt and pepper.",
            "Arrange cucumber slices and crackers on a plate.",
            "Spoon tuna mixture alongside. Serve with lemon.",
        ],
        "nutrients": {"calories": 310, "protein_g": 34, "carbs_g": 20, "fat_g": 8, "fibre_g": 2},
    },
    {
        "id": "cheese-fiber-combo-plate",
        "title": "Cheese & Fibre Combo Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "Sliced cheddar or Swiss cheese presented with fanned pear wedges and a cluster of almonds.",
        "servings": 1,
        "ingredients": [
            "60 g cheddar or Swiss cheese, sliced",
            "1 pear, cored and sliced",
            "30 g almonds",
            "4–6 whole-grain crackers",
        ],
        "steps": [
            "Arrange cheese, pear slices, almonds and crackers on a plate.",
        ],
        "nutrients": {"calories": 420, "protein_g": 18, "carbs_g": 32, "fat_g": 24, "fibre_g": 5},
    },
    {
        "id": "peanut-butter-comfort-plate",
        "title": "Peanut Butter Comfort Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "A scoop of peanut butter served with sliced bananas and whole-grain toast or rice cakes.",
        "servings": 1,
        "ingredients": [
            "2 tbsp (32 g) natural peanut butter",
            "1 banana, sliced",
            "2 rice cakes or 2 slices whole-grain toast",
        ],
        "steps": [
            "Spread peanut butter on rice cakes or toast.",
            "Top with banana slices and serve.",
        ],
        "nutrients": {"calories": 350, "protein_g": 12, "carbs_g": 44, "fat_g": 16, "fibre_g": 5},
    },
    {
        "id": "cottage-cheese-comeback-plate",
        "title": "Cottage Cheese Comeback Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "A bowl of cottage cheese topped with pineapple chunks or berries and a sprinkle of sunflower seeds.",
        "servings": 1,
        "ingredients": [
            "200 g low-fat cottage cheese",
            "80 g pineapple chunks or mixed berries",
            "1 tbsp (10 g) sunflower seeds",
            "Drizzle of honey (optional)",
        ],
        "steps": [
            "Spoon cottage cheese into a bowl.",
            "Top with fruit and sunflower seeds.",
            "Drizzle honey if using.",
        ],
        "nutrients": {"calories": 260, "protein_g": 26, "carbs_g": 24, "fat_g": 6, "fibre_g": 3},
    },
    {
        "id": "smoked-salmon-light-plate",
        "title": "Smoked Salmon Light Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "Ribbons of smoked salmon paired with a dollop of cream cheese, cucumber rounds and crackers.",
        "servings": 1,
        "ingredients": [
            "80 g smoked salmon",
            "2 tbsp (30 g) reduced-fat cream cheese",
            "½ cucumber, sliced into rounds",
            "6 whole-grain crackers",
            "Fresh dill and lemon to serve",
        ],
        "steps": [
            "Arrange salmon, cucumber rounds and crackers on a plate.",
            "Serve cream cheese alongside.",
            "Garnish with dill and lemon.",
        ],
        "nutrients": {"calories": 300, "protein_g": 22, "carbs_g": 18, "fat_g": 14, "fibre_g": 2},
    },
    {
        "id": "bean-crunch-plate",
        "title": "Bean & Crunch Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "Rinsed chickpeas lightly oiled and seasoned, served with crunchy carrot sticks and crackers.",
        "servings": 1,
        "ingredients": [
            "½ can (≈200 g) chickpeas, drained and rinsed",
            "1 tsp olive oil",
            "Pinch smoked paprika and salt",
            "2 medium carrots, cut into sticks",
            "4–6 whole-grain crackers",
        ],
        "steps": [
            "Toss chickpeas with olive oil, paprika and salt.",
            "Arrange on plate with carrot sticks and crackers.",
        ],
        "nutrients": {"calories": 300, "protein_g": 12, "carbs_g": 44, "fat_g": 8, "fibre_g": 10},
    },
    {
        "id": "turkey-roll-ups-plate",
        "title": "Turkey Roll-Ups Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "Slices of deli turkey rolled up with cheese, arranged neatly alongside pickles and crackers.",
        "servings": 1,
        "ingredients": [
            "100 g deli turkey breast slices",
            "30 g Swiss or cheddar cheese slices",
            "4 whole-grain crackers",
            "4 dill pickles or cucumber slices",
            "1 tsp mustard (optional)",
        ],
        "steps": [
            "Lay turkey slices flat; place cheese in the centre and roll up.",
            "Arrange rolls alongside crackers and pickles.",
            "Serve with mustard if desired.",
        ],
        "nutrients": {"calories": 260, "protein_g": 28, "carbs_g": 14, "fat_g": 10, "fibre_g": 1},
    },
    {
        "id": "avocado-egg-upgrade-plate",
        "title": "Avocado & Egg Upgrade Plate",
        "category": "No-Cook Healthy Snack Plates",
        "description": "Mashed avocado spread on whole-grain toast, plated alongside a halved boiled egg.",
        "servings": 1,
        "ingredients": [
            "½ avocado (≈80 g), mashed",
            "2 slices whole-grain toast",
            "1 hard-boiled egg, halved",
            "Salt, pepper and chilli flakes",
        ],
        "steps": [
            "Toast bread.",
            "Mash avocado with salt and pepper; spread on toast.",
            "Serve with halved boiled egg and a sprinkle of chilli flakes.",
        ],
        "nutrients": {"calories": 350, "protein_g": 16, "carbs_g": 28, "fat_g": 20, "fibre_g": 7},
    },
    {
        "id": "snack-plate-feels-like-meal",
        "title": "Snack Plate That Feels Like a Meal",
        "category": "No-Cook Healthy Snack Plates",
        "description": "A versatile grazing board with cheese cubes, boiled eggs, deli meat, fresh fruit, nuts and crackers.",
        "servings": 1,
        "ingredients": [
            "40 g cheddar cheese, cubed",
            "1 hard-boiled egg, halved",
            "40 g deli meat (turkey or chicken)",
            "1 small apple or handful of grapes",
            "30 g mixed nuts",
            "4–6 whole-grain crackers",
        ],
        "steps": [
            "Arrange all items on a large plate or board.",
            "Serve immediately.",
        ],
        "nutrients": {"calories": 480, "protein_g": 28, "carbs_g": 32, "fat_g": 26, "fibre_g": 4},
    },

    # ── QUICK MEALS USING GROCERY HACKS ────────────────────────────────────
    {
        "id": "lazy-sandwich-system",
        "title": "Lazy Sandwich System",
        "category": "Quick Grocery-Hack Meals",
        "description": "Pre-stage sandwich components so you can assemble wraps or sandwiches with zero prep instantly.",
        "servings": 1,
        "ingredients": [
            "2 slices whole-grain bread or 1 large wrap",
            "60 g deli turkey or chicken",
            "30 g cheese of choice",
            "Handful mixed salad leaves",
            "2 tbsp hummus or light mayo",
            "Sliced tomato or cucumber",
        ],
        "steps": [
            "Spread hummus or mayo on bread.",
            "Layer turkey, cheese, salad and tomato.",
            "Press together and slice. Serve immediately.",
        ],
        "nutrients": {"calories": 380, "protein_g": 28, "carbs_g": 36, "fat_g": 14, "fibre_g": 4},
    },
    {
        "id": "quick-tuna-sandwich",
        "title": "Quick Tuna Sandwich",
        "category": "Quick Grocery-Hack Meals",
        "description": "Canned tuna mixed with a little yoghurt or mayo, served on whole-grain bread with spinach.",
        "servings": 1,
        "ingredients": [
            "1 can (185 g) tuna in springwater, drained",
            "1 tbsp (15 g) light mayonnaise or Greek yoghurt",
            "2 slices whole-grain bread",
            "Handful baby spinach",
            "Lemon squeeze, salt and pepper",
        ],
        "steps": [
            "Mix tuna with mayo, lemon, salt and pepper.",
            "Layer spinach on bread; top with tuna mixture.",
            "Close sandwich and serve.",
        ],
        "nutrients": {"calories": 360, "protein_g": 38, "carbs_g": 30, "fat_g": 8, "fibre_g": 3},
    },
    {
        "id": "mashed-bean-toast",
        "title": "Mashed Bean Toast",
        "category": "Quick Grocery-Hack Meals",
        "description": "Canned beans lightly mashed with a fork, drizzled with olive oil or lemon, and spread over bread.",
        "servings": 1,
        "ingredients": [
            "½ can (≈200 g) cannellini or butter beans, drained",
            "2 slices whole-grain bread, toasted",
            "1 tbsp (15 ml) extra-virgin olive oil",
            "Squeeze of lemon",
            "Salt, pepper, chilli flakes",
        ],
        "steps": [
            "Mash beans with a fork, leaving some whole.",
            "Season with olive oil, lemon, salt, pepper and chilli.",
            "Spread generously on toast.",
        ],
        "nutrients": {"calories": 340, "protein_g": 18, "carbs_g": 48, "fat_g": 8, "fibre_g": 10},
    },
    {
        "id": "yogurt-fruit-bowl",
        "title": "Yoghurt & Fruit Bowl",
        "category": "Quick Grocery-Hack Meals",
        "description": "A simple assembly of plain Greek yoghurt, a sliced banana and a sprinkle of raw oats.",
        "servings": 1,
        "ingredients": [
            "180 g full-fat Greek yoghurt",
            "1 banana, sliced",
            "2 tbsp (20 g) rolled oats",
            "1 tbsp (15 ml) honey",
            "Pinch cinnamon",
        ],
        "steps": [
            "Spoon yoghurt into a bowl.",
            "Top with banana, oats, honey and cinnamon.",
        ],
        "nutrients": {"calories": 340, "protein_g": 16, "carbs_g": 52, "fat_g": 8, "fibre_g": 4},
    },
]

CATEGORIES = list(dict.fromkeys(r["category"] for r in RECIPES))

if __name__ == "__main__":
    print(f"Total recipes: {len(RECIPES)}")
    for cat in CATEGORIES:
        count = sum(1 for r in RECIPES if r["category"] == cat)
        print(f"  {cat}: {count}")
